# Project information
site_name: "ARETE HUB"
site_description: "ARETE - PHYSICS BOOK."
site_author: "ARETE"
site_url: "https://lain-source.github.io/PHYSICS/"

# Copyright
copyright: "&copy; 2023 DAYLIT"

# Repository
repo_name: "GitHub"
repo_url: "https://github.com/lain-source/PHYS-BOOK-LAUNCH"
edit_uri: "https://github.com/lain-source/PHYS-BOOK-LAUNCH"

# Configuration
docs_dir: "docs"
theme:
  name: "material"
  language: "en"
  shortcuts:
    help: 191 # ?
    next: 78 # n
    previous: 80 # p
    search: 83 # s
  palette:
    primary: "blue"
    accent: "blue"
  features:
    - tabs
  font:
    text: 'Ubuntu'
  #code: 'Ubuntu Mono'
  #icon:
  #logo: 'Aretelogo.png'
  #favicon: 'assets/images/favicon.ico'
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime




# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - md_in_html
  - mdx_math:
      enable_dollar_delimiter: true
  - toc:
      permalink: true
      separator: "_"

  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.arithmatex:
      generic: true


plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en
  - social:


        

# Customization
extra_javascript:
  - "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js?config=TeX-MML-AM_CHTML"
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - "assets/css/custom.css"
extra:
  manifest: "manifest.json"
  social:
    - icon: "fontawesome/brands/github-alt"
      link: "https://github.com"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com"

# Page tree
nav:
  - "Announcements": "index.md"
  - "PHYSICS": "Physics.md"
  - "Labs": "Labs.md"
  

